### ISSUE TITLE
App crashes while opening 

### ISSUE THREAD

**Issue by Felix-Kyun** [MuntashirAkon/BatteryChargeLimiter#19] opened 2023-01-05 18:05 UTC
Welp i installed the app and tried to open it and it opened but it crashed as soon as I clicked enable it crahsed and now it doesn't even open 
Logs : [bcl.log](https://github.com/MuntashirAkon/BatteryChargeLimiter/files/10354573/bcl.log)

**Comment by nfriedly** [comment] 2023-02-08 17:46
Same here - I'm using a moto g100 running LineageOS 20 (Android 13), rooted with magisk. The older Battery Charge Limit app that this is based off of does work, so I switched to that one for now.

I installed through f-droid, if that makes a difference.

**Comment by MuntashirAkon** [comment] 2024-07-04 14:22
Duplicate of #24

**Closed by MuntashirAkon** 2024-07-04 14:22 UTC
